from typing import Final

AUTH0_CREDENTIALS: Final = "AUTH0_CREDENTIALS"
AUTH0_DOMAIN: Final = "AUTH0_DOMAIN"
AUTH0_API_AUDIENCE: Final = "AUTH0_API_AUDIENCE"
AUTH0_ALGORITHMS: Final = "AUTH0_ALGORITHMS"
AUTH0_ISSUER: Final = "AUTH0_ISSUER"
